spring:
  application:
    name: team
  datasource:
    # create a file for h2 db data to persist
    # use jdbc:h2:mem:testdb for ephemeral db
    url: jdbc:h2:file:/data/f1-manager-app
    # use custom username and password
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  h2:
    # enable h2 console
    console:
      path: /h2-console
      enabled: true
      settings:
        # disable remote access to db
        web-allow-others: false
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    # initialize default script data defined after tables are created
    defer-datasource-initialization: true
    # initialize creation of empty tables
    hibernate:
      # ddl-auto: update
      # drop and create new database for first inits
      ddl-auto: create
  # for initialization at startup
  # use it to initialize db using scripts
  sql:
    init:
      mode: always
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8071/

# custom port
server:
  port: 8081
  servletPath: team

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    statusPageUrlPath: /${server.servletPath}/info
    healthCheckUrlPath: /${server.servletPath}/health

someValue: comingFromConfigServer
